GET http://localhost:5000/

### 
GET http://localhost:5000/api/admin/deadlock/teams

###

POST http://localhost:5000/api/admin/deadlock/match
Content-Type: application/json

{}


###
POST http://localhost:5000/api/admin/deadlock/team
Content-Type: application/json

{
  "name": "Test 2",
  "members": ["J", "K", "L"]
}
###
POST http://localhost:5000/api/admin/deadlock/match
Content-Type: application/json

{
  "teamA": "698a6484299bdedb54465093",
  "teamB": "698a645f299bdedb54465091"
}

###
PATCH http://localhost:5000/api/admin/deadlock/match/698a64ef299bdedb5446509e/teams
Content-Type: application/json

{
  "teamA": "698a6484299bdedb54465093",
  "teamB": "698a645f299bdedb54465091"
}

### 
PATCH http://localhost:5000/api/admin/deadlock/match/6982297f3adcaf19377c84ef/swap

###

PATCH http://localhost:5000/api/admin/deadlock/match/6982297f3adcaf19377c84ef/reset

###
PATCH http://localhost:5000/api/admin/deadlock/match/698e6125e463e04b7bdb1153/finish
Content-Type: application/json

{
  "winner": "698e4a2d5a116a5a6b844c37"
}

### Finish Match (New - By Team ID Only)
PATCH http://localhost:5000/api/admin/deadlock/finish
Content-Type: application/json

{
    "winner": "698e4a2d5a116a5a6b844c37"
}
###

POST http://localhost:5000/api/admin/deadlock/solve
Content-Type: application/json

{
  "matchId": "698a64ef299bdedb5446509e",
  "solvingTeamId": "698a6484299bdedb54465093"
}

###

POST http://localhost:5000/api/public/deadlock/submit
Content-Type: application/json

{
  "matchId": "69899724a5cdbcd1503a8662",
  "teamId": "69899724a5cdbcd1503a865d",
  "questionId": "6698967c8e44e2d323aca97ba",
  "answer": "42"
}


### Seed Deadlock (DEV)
POST http://localhost:5000/api/dev/deadlock
Content-Type: application/json


@matchId = Y69899724a5cdbcd1503a8662
@teamId = 69899724a5cdbcd1503a865d
@questionId = 6698967c8e44e2d323aca97ba"

### Submit Deadlock Solution (Python example)
POST http://localhost:5000/api/public/deadlock/submit
Content-Type: application/json

{
  "matchId": "{{matchId}}",
  "teamId": "{{teamId}}",
  "questionId": "{{questionId}}",
  "language": "python",
  "code": "a, b = map(int, input().split())\nprint(a * b)"
}

###

@matchId = 698996c7a5cdbcd1503a8653

### Get Deadlock Match by ID
GET http://localhost:5000/api/public/deadlock/match/{{matchId}}



