const path = require('path');
const mongoose = require('mongoose');
const DeadlockQuestion = require('../model/deadlockQuestion');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const getTpl = (fn, pyP, cppP, jvP) => ({
    python: `class Solution:\n    def ${fn}(self, ${pyP}):\n        # Write solution here\n        `,
    cpp: `class Solution {\npublic:\n    // Write solution here\n    auto ${fn}(${cppP}) {\n        \n    }\n};`,
    java: `class Solution {\n    // Write solution here\n    public Object ${fn}(${jvP}) {\n        return null;\n    }\n}`
});

const q = (t, d, f, c, p, cp, j, tcs, diff) => ({
    title: t,
    description: d,
    difficulty: diff,
    category: c,
    functionName: f,
    parameters: {
        python: p,
        cpp: cp,
        java: j
    },
    templates: getTpl(f, p, cp, j),
    testCases: tcs.map((tc, i) => ({ input: String(tc.in), output: String(tc.out).trim(), isHidden: i > 0 }))
});

const EASY = [
    q("Is Perfect Square", "Analyze the given integer n and return a boolean value indicating if it is a perfect square.", "isPerfectSquare", "Logic", "n", "int n", "int n", [{ in: 16, out: true }, { in: 14, out: false }, { in: 1, out: true }], "easy"),
    q("Power of Two", "Evaluate the integer n and return true if it is a power of two, otherwise return false.", "isPowerOfTwo", "Logic", "n", "int n", "int n", [{ in: 8, out: true }, { in: 7, out: false }, { in: 1, out: true }], "easy"),
    q("Century Year", "Check the given year y and return a boolean value indicating if it is a century year (divisible by 100).", "isCentury", "Logic", "y", "int y", "int y", [{ in: 1900, out: true }, { in: 2024, out: false }, { in: 2000, out: true }], "easy"),
    q("Double Sum", "Calculate and return twice the sum of the two integers a and b.", "doubleSum", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "10|5", out: 30 }, { in: "2|3", out: 10 }, { in: "0|0", out: 0 }], "easy"),
    q("Average Floor", "Compute the average of integers a and b, and return the floor value as an integer.", "avgFloor", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "10|5", out: 7 }, { in: "2|4", out: 3 }, { in: "1|1", out: 1 }], "easy"),
    q("Is Within Range", "Verify if the integer n is within the inclusive range of 10 to 50 and return the result as a boolean.", "isInRange", "Logic", "n", "int n", "int n", [{ in: 25, out: true }, { in: 5, out: false }, { in: 55, out: false }], "easy"),
    q("Modulo Seven", "Determine and return the remainder when the integer n is divided by 7.", "modSeven", "Logic", "n", "int n", "int n", [{ in: 15, out: 1 }, { in: 7, out: 0 }, { in: 50, out: 1 }], "easy"),
    q("Cube Volume", "Calculate and return the volume of a cube with the given side length s.", "cubeVol", "Logic", "s", "int s", "int s", [{ in: 3, out: 27 }, { in: 5, out: 125 }, { in: 2, out: 8 }], "easy"),
    q("Perimeter Rect", "Calculate and return the perimeter of a rectangle with the given length l and width w.", "periRect", "Logic", "l, w", "int l, int w", "int l, int w", [{ in: "10|5", out: 30 }, { in: "4|4", out: 16 }, { in: "2|1", out: 6 }], "easy"),
    q("First Character", "Extract and return the first character of the given string s.", "firstChar", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: "h" }, { in: "\"world\"", out: "w" }, { in: "\"a\"", out: "a" }], "easy"),
    q("Last Character", "Identify and return the final character of the given string s.", "lastChar", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: "o" }, { in: "\"abc\"", out: "c" }, { in: "\"z\"", out: "z" }], "easy"),
    q("String Repeat", "Construct and return a new string by concatenating the given string s with itself.", "repeatTwice", "Strings", "s", "string s", "String s", [{ in: "\"hi\"", out: "hihi" }, { in: "\"o\"", out: "oo" }, { in: "\"abc\"", out: "abcabc" }], "easy"),
    q("Contains Space", "Determine if the given string s contains at least one space character and return a boolean result.", "hasSpace", "Strings", "s", "string s", "String s", [{ in: "\"a b\"", out: true }, { in: "\"ab\"", out: false }, { in: "\" \"", out: true }], "easy"),
    q("Uppercase Check", "Check if the given character c is an uppercase letter (A-Z) and return the corresponding boolean.", "isUpper", "Strings", "c", "char c", "char c", [{ in: "'A'", out: true }, { in: "'a'", out: false }, { in: "'Z'", out: true }], "easy"),
    q("Lowercase Check", "Verify if the character c is a lowercase letter (a-z) and return true or false.", "isLower", "Strings", "c", "char c", "char c", [{ in: "'a'", out: true }, { in: "'A'", out: false }, { in: "'z'", out: true }], "easy"),
    q("Vowel Check", "Assess if the given character c is a vowel (a, e, i, o, u) and return the result as a boolean.", "isVowel", "Strings", "c", "char c", "char c", [{ in: "'a'", out: true }, { in: "'e'", out: true }, { in: "'b'", out: false }], "easy"),
    q("Digit Check", "Return true if the character c represents a numerical digit (0-9), otherwise return false.", "isDigit", "Strings", "c", "char c", "char c", [{ in: "'5'", out: true }, { in: "'a'", out: false }, { in: "'0'", out: true }], "easy"),
    q("Concat Space", "Join strings s1 and s2 with a single space in between and return the resulting string.", "concatSpace", "Strings", "s1, s2", "string s1, string s2", "String s1, String s2", [{ in: "\"a\"|\"b\"", out: "a b" }, { in: "\"hi\"|\"yo\"", out: "hi yo" }, { in: "\"1\"|\"2\"", out: "1 2" }], "easy"),
    q("Absolute Value", "Calculate and return the absolute value of the given integer n.", "absolute", "Logic", "n", "int n", "int n", [{ in: -5, out: 5 }, { in: 10, out: 10 }, { in: 0, out: 0 }], "easy"),
    q("Is Large Num", "Check if the integer n is strictly greater than 1000 and return a boolean value.", "isLarge", "Logic", "n", "int n", "int n", [{ in: 1500, out: true }, { in: 500, out: false }, { in: 1001, out: true }], "easy"),
    q("Max of Three", "Find and return the maximum value among the three given integers a, b, and c.", "maxOfThree", "Logic", "a, b, c", "int a, int b, int c", "int a, int b, int c", [{ in: "1|5|3", out: 5 }, { in: "10|2|8", out: 10 }, { in: "0|0|1", out: 1 }], "easy"),
    q("Min of Three", "Identify and return the minimum value among the three given integers a, b, and c.", "minOfThree", "Logic", "a, b, c", "int a, int b, int c", "int a, int b, int c", [{ in: "1|5|3", out: 1 }, { in: "10|2|8", out: 2 }, { in: "0|-1|5", out: -1 }], "easy"),
    q("Next Fibonacci", "Given a Fibonacci number n, return the next immediate number in the sequence.", "nextFib", "Logic", "n", "int n", "int n", [{ in: 5, out: 8 }, { in: 1, out: 2 }, { in: 3, out: 5 }], "easy"),
    q("First Array Elem", "Retrieve and return the first element of the given integer array nums.", "firstElem", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 1 }, { in: "[5,0]", out: 5 }, { in: "[100]", out: 100 }], "easy"),
    q("Array Length", "Calculate and return the total number of elements present in the integer array nums.", "arrLen", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 3 }, { in: "[5,0]", out: 2 }, { in: "[]", out: 0 }], "easy"),
    q("Has Target Num", "Determine if the number 5 is present within the array nums and return the result as a boolean.", "hasFive", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,5,3]", out: true }, { in: "[2,4]", out: false }, { in: "[5,5]", out: true }], "easy"),
    q("Sum First Two", "Calculate and return the sum of the first two elements in the array nums.", "sumFirstTwo", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 3 }, { in: "[10,20]", out: 30 }, { in: "[0,0]", out: 0 }], "easy"),
    q("Reverse Boolean", "Perform a logical NOT operation on the boolean b and return the inverse result.", "logicalNot", "Logic", "b", "bool b", "boolean b", [{ in: true, out: false }, { in: false, out: true }, { in: true, out: false }], "easy"),
    q("Both True", "Evaluate both booleans a and b and return true if both are true, otherwise return false.", "logicalAnd", "Logic", "a, b", "bool a, bool b", "boolean a, boolean b", [{ in: "true|true", out: true }, { in: "true|false", out: false }, { in: "false|false", out: false }], "easy"),
    q("Either True", "Check booleans a and b and return true if at least one of them is true.", "logicalOr", "Logic", "a, b", "bool a, bool b", "boolean a, boolean b", [{ in: "true|false", out: true }, { in: "false|false", out: false }, { in: "true|true", out: true }], "easy"),
    q("Different Sign", "Determine if integers a and b have different signs and return a boolean result.", "differentSign", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "5|-2", out: true }, { in: "10|5", out: false }, { in: "-3|-3", out: false }], "easy"),
    q("Starts with B", "Check if the first character of string s is the uppercase letter 'B' and return true or false.", "startsWithB", "Strings", "s", "string s", "String s", [{ in: "\"Ball\"", out: true }, { in: "\"apple\"", out: false }, { in: "\"B\"", out: true }], "easy"),
    q("Ends with X", "Verify if the given string s ends with the uppercase character 'X' and return a boolean value.", "endsWithX", "Strings", "s", "string s", "String s", [{ in: "\"MAX\"", out: true }, { in: "\"HEX\"", out: true }, { in: "\"box\"", out: false }], "easy"),
    q("Char Count Z", "Count and return the total number of occurrences of the character 'z' within the string s.", "countZ", "Strings", "s", "string s", "String s", [{ in: "\"buzz\"", out: 2 }, { in: "\"abc\"", out: 0 }, { in: "\"zzz\"", out: 3 }], "easy"),
    q("Repeat Three", "Concatenate the given string s three times and return the resulting consolidated string.", "repeatThree", "Strings", "s", "string s", "String s", [{ in: "\"a\"", out: "aaa" }, { in: "\"hi\"", out: "hihihi" }, { in: "\"!\"", out: "!!!" }], "easy"),
    q("Is Multiple Of", "Analyze integers a and b to determine if a is a multiple of b, returning a boolean result.", "isMultiple", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "10|5", out: true }, { in: "7|3", out: false }, { in: "100|10", out: true }], "easy"),
    q("Triangle Type", "Return the string 'equilateral' if all three side lengths a, b, and c are equal; otherwise return 'other'.", "triType", "Logic", "a, b, c", "int a, int b, int c", "int a, int b, int c", [{ in: "5|5|5", out: "equilateral" }, { in: "3|4|5", out: "other" }, { in: "10|10|10", out: "equilateral" }], "easy"),
    q("Is Even Length", "Determine if the total length of the string s is an even number and return true or false.", "isEvenLen", "Strings", "s", "string s", "String s", [{ in: "\"abcd\"", out: true }, { in: "\"abc\"", out: false }, { in: "\"\"", out: true }], "easy"),
    q("Char at Index", "Retrieve and return the character located at index 2 of the given string s.", "charAtTwo", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: "l" }, { in: "\"world\"", out: "r" }, { in: "\"abc\"", out: "c" }], "easy"),
    q("Sum of Squares", "Calculate and return the sum of the squares of integers a and b.", "sumSquares", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "3|4", out: 25 }, { in: "1|1", out: 2 }, { in: "0|5", out: 25 }], "easy"),
    q("Last Arr Elem", "Identify and return the final element in the integer array nums.", "lastElem", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 3 }, { in: "[10,0]", out: 0 }, { in: "[5]", out: 5 }], "easy"),
    q("Area of Circle", "Calculate the area of a circle with radius r and return the floor value as an integer (use 3 as an approximation for PI).", "circleArea", "Logic", "r", "int r", "int r", [{ in: 2, out: 12 }, { in: 1, out: 3 }, { in: 3, out: 27 }], "easy"),
    q("Is Odd Sum", "Assess the sum of integers a and b and return a boolean value indicating if it is an odd number.", "isOddSum", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "5|2", out: true }, { in: "10|10", out: false }, { in: "0|1", out: true }], "easy"),
    q("Digit Count 3", "Verify if the given integer n is a three-digit number (100 to 999 inclusive) and return true or false.", "hasThreeDigits", "Logic", "n", "int n", "int n", [{ in: 150, out: true }, { in: 50, out: false }, { in: 1000, out: false }], "easy"),
    q("Middle Value", "Determine and return the middle value among the three given integers a, b, and c when sorted.", "middleNum", "Logic", "a, b, c", "int a, int b, int c", "int a, int b, int c", [{ in: "1|5|3", out: 3 }, { in: "10|2|8", out: 8 }, { in: "0|-1|5", out: 0 }], "easy"),
    q("Same Last Digit", "Check if integers a and b have the same last digit and return the corresponding boolean value.", "sameLastDigit", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "27|57", out: true }, { in: "10|12", out: false }, { in: "5|15", out: true }], "easy"),
    q("Div 3 and 5", "Verify if the integer n is divisible by both 3 and 5, and return a boolean result.", "divThreeFive", "Logic", "n", "int n", "int n", [{ in: 15, out: true }, { in: 10, out: false }, { in: 30, out: true }], "easy"),
    q("String Trim", "Remove any leading or trailing whitespace from the string s and return the cleaned string.", "trimmed", "Strings", "s", "string s", "String s", [{ in: "\" hi \"", out: "hi" }, { in: "\"abc\"", out: "abc" }, { in: "\"  x\"", out: "x" }], "easy"),
    q("Is Letter", "Check if the given character c is an alphabetical letter (a-z or A-Z) and return a boolean.", "isLetter", "Strings", "c", "char c", "char c", [{ in: "'a'", out: true }, { in: "'1'", out: false }, { in: "'!'", out: false }], "easy"),
    q("Next Character", "Identify and return the character that immediately follows c in the ASCII sequence.", "nextChar", "Strings", "c", "char c", "char c", [{ in: "'a'", out: "b" }, { in: "'A'", out: "B" }, { in: "'0'", out: "1" }], "easy"),
    q("Prev Character", "Find and return the character that immediately precedes c in the ASCII sequence.", "prevChar", "Strings", "c", "char c", "char c", [{ in: "'b'", out: "a" }, { in: "'B'", out: "A" }, { in: "'1'", out: "0" }], "easy"),
    q("Check Bit Zero", "Assess the zeroth bit (least significant) of the integer n and return 1 if it is set, otherwise return 0.", "checkBitZero", "Logic", "n", "int n", "int n", [{ in: 5, out: 1 }, { in: 4, out: 0 }, { in: 0, out: 0 }], "easy"),
    q("Is Consonant", "Determine if the given character c is a consonant and return a boolean result.", "isConsonant", "Strings", "c", "char c", "char c", [{ in: "'b'", out: true }, { in: "'a'", out: false }, { in: "'z'", out: true }], "easy"),
    q("Double Array", "Transform the array nums by doubling each element and return the resulting new array.", "doubleArr", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2]", out: "[2,4]" }, { in: "[0]", out: "[0]" }, { in: "[-1]", out: "[-2]" }], "easy"),
    q("Only One True", "Execute an XOR logic operation on booleans a and b, returning true if exactly one is true.", "onlyOneTrue", "Logic", "a, b", "bool a, bool b", "boolean a, boolean b", [{ in: "true|false", out: true }, { in: "true|true", out: false }, { in: "false|false", out: false }], "easy"),
    q("Join with Dash", "Concatenate strings s1 and s2 with a dash '-' in between and return the result.", "joinDash", "Strings", "s1, s2", "string s1, string s2", "String s1, String s2", [{ in: "\"a\"|\"b\"", out: "a-b" }, { in: "\"z\"|\"y\"", out: "z-y" }, { in: "\"1\"|\"2\"", out: "1-2" }], "easy"),
    q("Length > 5", "Check if the total length of the string s is strictly greater than 5 and return a boolean value.", "isLongStr", "Strings", "s", "string s", "String s", [{ in: "\"hello world\"", out: true }, { in: "\"hi\"", out: false }, { in: "\"abcdef\"", out: true }], "easy"),
    q("Abs Difference", "Calculate and return the absolute difference between the two integers a and b.", "absDiff", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "10|5", out: 5 }, { in: "2|10", out: 8 }, { in: "0|0", out: 0 }], "easy"),
    q("Is Binary Digit", "Determine if the character c is either '0' or '1' and return true or false accordingly.", "isBinDigit", "Strings", "c", "char c", "char c", [{ in: "'0'", out: true }, { in: "'1'", out: true }, { in: "'2'", out: false }], "easy"),
    q("Triple Sum", "Calculate the sum of integers a, b, and c, then return three times that total.", "tripleSum", "Logic", "a, b, c", "int a, int b, int c", "int a, int b, int c", [{ in: "1|1|1", out: 9 }, { in: "0|5|0", out: 15 }, { in: "-1|1|0", out: 0 }], "easy")
];

const MEDIUM = [
    q("Evaluate Factorial", "Calculate the factorial of the integer n (the product of all positive integers up to n) and return the result as an integer.", "factorial", "Logic", "n", "int n", "int n", [{ in: 5, out: 120 }, { in: 3, out: 6 }, { in: 0, out: 1 }], "medium"),
    q("Identify Prime", "Assess the integer n and return a boolean value indicating whether it is a prime number (a number greater than 1 with no divisors other than 1 and itself).", "isPrime", "Logic", "n", "int n", "int n", [{ in: 7, out: true }, { in: 4, out: false }, { in: 2, out: true }], "medium"),
    q("Calculate Fib", "Compute and return the nth number in the Fibonacci sequence (where each number is the sum of the two preceding ones, starting from 0 and 1).", "fibonacci", "Logic", "n", "int n", "int n", [{ in: 5, out: 5 }, { in: 0, out: 0 }, { in: 1, out: 1 }], "medium"),
    q("Reverse String", "Reverse the order of characters in the given string s and return the result.", "reverseStr", "Strings", "s", "string s", "String s", [{ in: "\"abc\"", out: "cba" }, { in: "\"hi\"", out: "ih" }, { in: "\"\"", out: "" }], "medium"),
    q("Check Palindrome", "Verify if the string s is a palindrome (reads the same forwards and backwards) and return a boolean value.", "isPalindrome", "Strings", "s", "string s", "String s", [{ in: "\"aba\"", out: true }, { in: "\"abc\"", out: false }, { in: "\"racecar\"", out: true }], "medium"),
    q("Sum Array Logic", "Calculate and return the cumulative sum of all integers present in the array nums.", "sumArray", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 6 }, { in: "[10,-5]", out: 5 }, { in: "[]", out: 0 }], "medium"),
    q("Find Maximum", "Identify and return the largest numerical value within the given integer array nums.", "findMax", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,5,3]", out: 5 }, { in: "[-1,-10]", out: -1 }, { in: "[100]", out: 100 }], "medium"),
    q("Calculate GCD", "Compute and return the Greatest Common Divisor (GCD) of integers a and b (the largest positive integer that divides both numbers without a remainder).", "findGcd", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "12|8", out: 4 }, { in: "10|5", out: 5 }, { in: "7|3", out: 1 }], "medium"),
    q("Anagram Check", "Determine if strings s1 and s2 are anagrams (words formed by rearranging the letters of another using all original letters exactly once) and return true or false.", "isAnagram", "Strings", "s1, s2", "string s1, string s2", "String s1, String s2", [{ in: "\"listen\"|\"silent\"", out: true }, { in: "\"a\"|\"b\"", out: false }, { in: "\"abc\"|\"cba\"", out: true }], "medium"),
    q("Find Second Max", "Retrieve and return the second largest unique integer from the array nums.", "secondMax", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,5,3]", out: 3 }, { in: "[10,10,5]", out: 5 }, { in: "[1,2]", out: 1 }], "medium"),
    q("Binary to Int", "Convert the given binary string s into its equivalent base-10 integer and return it.", "binToInt", "Logic", "s", "string s", "String s", [{ in: "\"101\"", out: 5 }, { in: "\"111\"", out: 7 }, { in: "\"0\"", out: 0 }], "medium"),
    q("Count Vowels", "Count and return the total number of vowels (a, e, i, o, u) present in the string s.", "countVowels", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: 2 }, { in: "\"sky\"", out: 0 }, { in: "\"aeiou\"", out: 5 }], "medium"),
    q("Title Case Str", "Reformat the string s by capitalizing only the first character and converting the rest to lowercase.", "titleCase", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: "Hello" }, { in: "\"ABC\"", out: "Abc" }, { in: "\"x Y z\"", out: "X y z" }], "medium"),
    q("Identify Armstrong", "Check if the integer n is an Armstrong number (a number that is the sum of its own digits each raised to the power of the number of digits) and return a boolean.", "isArmstrong", "Logic", "n", "int n", "int n", [{ in: 153, out: true }, { in: 100, out: false }, { in: 370, out: true }], "medium"),
    q("Check Sorted", "Verify if the elements in the array nums are arranged in non-decreasing order, returning a boolean result.", "isSorted", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: true }, { in: "[3,2,1]", out: false }, { in: "[1,1,2]", out: true }], "medium"),
    q("Find Average", "Calculate the average of all elements in the array nums and return the floor value as an integer.", "arrayAverage", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 2 }, { in: "[10,20]", out: 15 }, { in: "[1,1,1]", out: 1 }], "medium"),
    q("Rotate String One", "Perform a left cyclic rotation on the string s by one position and return the resulting string.", "rotateLeftOne", "Strings", "s", "string s", "String s", [{ in: "\"abc\"", out: "bca" }, { in: "\"hello\"", out: "elloh" }, { in: "\"z\"", out: "z" }], "medium"),
    q("Word Counter", "Count and return the total number of words in the string s (assuming words are separated by a single space).", "countWords", "Strings", "s", "string s", "String s", [{ in: "\"hello world\"", out: 2 }, { in: "\"one\"", out: 1 }, { in: "\"a b c\"", out: 3 }], "medium"),
    q("Search Element", "Find the index of the integer x in the array nums and return it; return -1 if x is not found.", "searchIndex", "Arrays", "nums, x", "vector<int>& nums, int x", "int[] nums, int x", [{ in: "[1,2,3]|2", out: 1 }, { in: "[1,5]|10", out: -1 }, { in: "[0,0]|0", out: 0 }], "medium"),
    q("Calculate LCM", "Find and return the Least Common Multiple (LCM) of the two integers a and b (the smallest positive integer that is divisible by both numbers).", "findLcm", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "4|6", out: 12 }, { in: "10|5", out: 10 }, { in: "3|7", out: 21 }], "medium"),
    q("Sum of Digits", "Calculate and return the sum of all individual digits within the integer n.", "sumOfDigits", "Logic", "n", "int n", "int n", [{ in: 123, out: 6 }, { in: 105, out: 6 }, { in: 0, out: 0 }], "medium"),
    q("Remove Char X", "Construct and return a new string by removing all occurrences of the character x from the string s.", "removeChar", "Strings", "s, x", "string s, char x", "String s, char x", [{ in: "\"hello\"|'l'", out: "heo" }, { in: "\"abc\"|'z'", out: "abc" }, { in: "\"zzz\"|'z'", out: "" }], "medium"),
    q("Count Odds", "Count and return the total number of odd integers present in the array nums.", "countOdds", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,4,5]", out: 3 }, { in: "[2,4]", out: 0 }, { in: "[3,3]", out: 2 }], "medium"),
    q("Merge Arrays", "Concatenate array b to the end of array a and return the resulting combined array.", "mergeLists", "Arrays", "a, b", "vector<int>& a, vector<int>& b", "int[] a, int[] b", [{ in: "[1,3]|[2,4]", out: "[1,2,3,4]" }, { in: "[]|[1]", out: "[1]" }, { in: "[0]|[0]", out: "[0,0]" }], "medium"),
    q("Compress String", "Compress the string s by replacing consecutive identical characters with the character followed by its count (e.g., aaabcc -> a3b1c2).", "compress", "Strings", "s", "string s", "String s", [{ in: "\"aaabcc\"", out: "a3b1c2" }, { in: "\"abc\"", out: "a1b1c1" }, { in: "\"aaaaa\"", out: "a5" }], "medium"),
    q("Toggle Case Str", "Return a new string where all uppercase letters in s are converted to lowercase and vice versa.", "toggleCase", "Strings", "s", "string s", "String s", [{ in: "\"Hello\"", out: "hELLO" }, { in: "\"abc\"", out: "ABC" }, { in: "\"123\"", out: "123" }], "medium"),
    q("Perfect Number", "Determine if the integer n is a perfect number (a positive integer that is equal to the sum of its positive divisors, excluding the number itself) and return true or false.", "isPerfect", "Logic", "n", "int n", "int n", [{ in: 28, out: true }, { in: 6, out: true }, { in: 10, out: false }], "medium"),
    q("Digit Max Value", "Identify and return the maximum digit value found within the integer n.", "maxDigit", "Logic", "n", "int n", "int n", [{ in: 12345, out: 5 }, { in: 901, out: 9 }, { in: 0, out: 0 }], "medium"),
    q("Primes Count To", "Count and return the total number of prime numbers less than or equal to the integer n.", "primesUpToN", "Logic", "n", "int n", "int n", [{ in: 10, out: 4 }, { in: 20, out: 8 }, { in: 2, out: 1 }], "medium"),
    q("Rotate Array One", "Shift all elements in the array nums to the right by one position (cyclic) and return the resulting array.", "rotateArrRight", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: "[3,1,2]" }, { in: "[5]", out: "[5]" }, { in: "[0,1]", out: "[1,0]" }], "medium"),
    q("Median of Array", "Find and return the median element of the integer array nums (assuming it's already sorted).", "findMedian", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,4,5]", out: 3 }, { in: "[1,10,100]", out: 10 }, { in: "[5,5,5]", out: 5 }], "medium"),
    q("Remove Dups", "Calculate and return the number of unique elements present in the integer array nums.", "uniqueCount", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,1,2,2,3]", out: 3 }, { in: "[1,2,3]", out: 3 }, { in: "[1,1,1]", out: 1 }], "medium"),
    q("Intersection Cnt", "Count and return the number of common unique elements between arrays a and b.", "intersectCount", "Arrays", "a, b", "vector<int>& a, vector<int>& b", "int[] a, int[] b", [{ in: "[1,2,3]|[2,3,4]", out: 2 }, { in: "[1]|[2]", out: 0 }, { in: "[0,1]|[1,2]", out: 1 }], "medium"),
    q("Reverse Array In", "Reverse the order of all elements in the given integer array nums and return the result.", "reverseArray", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: "[3,2,1]" }, { in: "[10]", out: "[10]" }, { in: "[]", out: "[]" }], "medium"),
    q("Multiply Arr", "Calculate and return the product of all numerical elements present in the array nums.", "arrProd", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,4]", out: 24 }, { in: "[5]", out: 5 }, { in: "[1,10,0]", out: 10 }], "medium"),
    q("Filter Positives", "Return a new array containing only the positive integers (greater than zero) from the array nums.", "positivesOnly", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,-1,2,-2]", out: "[1,2]" }, { in: "[-10]", out: "[]" }, { in: "[5,0]", out: "[5]" }], "medium"),
    q("Search Substr", "Find the starting index of substring sub within string s and return it; return -1 if sub is not found.", "findSubstr", "Strings", "s, sub", "string s, string sub", "String s, String sub", [{ in: "\"hello\"|\"ell\"", out: 1 }, { in: "\"abc\"|\"z\"", out: -1 }, { in: "\"yo\"|\"yo\"", out: 0 }], "medium"),
    q("Char Freq A", "Count and return the total number of times the character 'a' occurs within the string s.", "aFrequency", "Strings", "s", "string s", "String s", [{ in: "\"banana\"", out: 3 }, { in: "\"abc\"", out: 1 }, { in: "\"xyz\"", out: 0 }], "medium"),
    q("Next Prime Num", "Identify and return the smallest prime number that is strictly greater than the integer n.", "nextPrime", "Logic", "n", "int n", "int n", [{ in: 7, out: 11 }, { in: 10, out: 11 }, { in: 2, out: 3 }], "medium"),
    q("Is Base Two", "Determine if the integer n is a power of 2 using bitwise operations and return a boolean.", "isBitPower2", "Logic", "n", "int n", "int n", [{ in: 16, out: true }, { in: 15, out: false }, { in: 1, out: true }], "medium"),
    q("Count Leaves", "Count and return the total number of trailing zeros in the binary representation of the integer n.", "trailingZeros", "Logic", "n", "int n", "int n", [{ in: 8, out: 3 }, { in: 10, out: 1 }, { in: 1, out: 0 }], "medium"),
    q("Square Sum List", "Calculate and return the sum of the squares of all elements present in the integer array nums.", "sumOfSqArray", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3]", out: 14 }, { in: "[5]", out: 25 }, { in: "[0,0,1]", out: 1 }], "medium"),
    q("Median Of Three", "Identify and return the median value among the three given integers a, b, and c.", "medianVal", "Logic", "a, b, c", "int a, int b, int c", "int a, int b, int c", [{ in: "1|5|3", out: 3 }, { in: "10|2|8", out: 8 }, { in: "0|-1|5", out: 0 }], "medium"),
    q("Sum Array Odd", "Calculate and return the cumulative sum of all odd integers present in the array nums.", "sumOddArray", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,4,5]", out: 9 }, { in: "[2,4]", out: 0 }, { in: "[1,1,1]", out: 3 }], "medium"),
    q("Middle Element", "Retrieve and return the middle element of the array nums; if length is even, return the first of the two middle elements.", "middleArray", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,4,5]", out: 3 }, { in: "[1,2,3,4]", out: 3 }, { in: "[5]", out: 5 }], "medium"),
    q("Max Difference", "Find two elements in the array nums with the maximum difference and return that difference value.", "maxDiff", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,5,3]", out: 4 }, { in: "[10,-5]", out: 15 }, { in: "[1,1,1]", out: 0 }], "medium"),
    q("Find Target Pair", "Determine if there exists a pair of integers in array nums that sum up to target, returning true or false.", "hasPairSum", "Arrays", "nums, target", "vector<int>& nums, int target", "int[] nums, int target", [{ in: "[1,2,3]|5", out: true }, { in: "[1,1]|10", out: false }, { in: "[0,5,0]|5", out: true }], "medium"),
    q("Join With Space", "Join all strings in the words array into a single sentence separated by spaces and return the result.", "joinSentence", "Strings", "words", "vector<string>& words", "String[] words", [{ in: "[\"hi\",\"there\"]", out: "hi there" }, { in: "[\"a\"]", out: "a" }, { in: "[]", out: "" }], "medium"),
    q("Filter By Length", "Identify all strings in the array s that have a length equal to n and return them as a new array.", "filterLen", "Strings", "s, n", "vector<string>& s, int n", "String[] s, int n", [{ in: "[\"a\",\"bb\",\"ccc\"]|2", out: "[\"bb\"]" }, { in: "[\"x\",\"y\"]|1", out: "[\"x\",\"y\"]" }, { in: "[]|5", out: "[]" }], "medium"),
    q("Pangram Check", "Verify if the string s is a pangram (a sentence containing every letter of the alphabet at least once) and return a boolean value.", "isPangram", "Strings", "s", "string s", "String s", [{ in: "\"the quick brown fox jumps over the lazy dog\"", out: true }, { in: "\"abc\"", out: false }, { in: "\"abcdefghijklmnopqrstuvwxyz\"", out: true }], "medium"),
    q("Vowel Index Sum", "Calculate and return the sum of the indices of all vowels present within the string s.", "sumVowelIdx", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: 5 }, { in: "\"abc\"", out: 0 }, { in: "\"aeiou\"", out: 10 }], "medium"),
    q("String Rotation", "Check if string s2 is a cyclic rotation of string s1 and return true or false.", "isRotation", "Strings", "s1, s2", "string s1, string s2", "String s1, String s2", [{ in: "\"abcde\"|\"cdeab\"", out: true }, { in: "\"abc\"|\"def\"", out: false }, { in: "\"a\"|\"a\"", out: true }], "medium"),
    q("Binary Gap", "Find and return the length of the longest sequence of zeros between two ones in the binary representation of integer n.", "binaryGap", "Logic", "n", "int n", "int n", [{ in: 9, out: 2 }, { in: 529, out: 4 }, { in: 20, out: 1 }], "medium"),
    q("Digit Product", "Calculate and return the product of all numerical digits within the integer n.", "digitProduct", "Logic", "n", "int n", "int n", [{ in: 123, out: 6 }, { in: 105, out: 0 }, { in: 55, out: 25 }], "medium"),
    q("Strong Number", "Determine if integer n is a strong number (sum of the factorials of its digits equals n) and return true or false.", "isStrong", "Logic", "n", "int n", "int n", [{ in: 145, out: true }, { in: 10, out: false }, { in: 1, out: true }], "medium"),
    q("Factor Count N", "Count and return the total number of positive factors for the given integer n.", "countDivisors", "Logic", "n", "int n", "int n", [{ in: 6, out: 4 }, { in: 10, out: 4 }, { in: 13, out: 2 }], "medium"),
    q("Arrange Digits", "Rearrange the digits of integer n to form the largest possible number and return it.", "largestRearrange", "Logic", "n", "int n", "int n", [{ in: 123, out: 321 }, { in: 901, out: 910 }, { in: 505, out: 550 }], "medium"),
    q("Even Index Sum", "Calculate and return the sum of all elements located at even indices within the array nums.", "evenIndexSum", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,4,5]", out: 9 }, { in: "[10]", out: 10 }, { in: "[1,1,1]", out: 2 }], "medium"),
    q("Is Power of 3", "Determine if the given integer n is a power of 3 and return the result as a boolean.", "isPowerOfThree", "Logic", "n", "int n", "int n", [{ in: 27, out: true }, { in: 10, out: false }, { in: 1, out: true }], "medium"),
    q("Char Frequency", "Identify and return the character that occurs most frequently within the string s.", "mostFrequent", "Strings", "s", "string s", "String s", [{ in: "\"banana\"", out: "a" }, { in: "\"abc\"", out: "a" }, { in: "\"zzz\"", out: "z" }], "medium")
];

const HARD = [
    q("Move Zeroes", "Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the non-zero elements.", "moveZeroes", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[0,1,0,3,12]", out: "[1,3,12,0,0]" }, { in: "[0]", out: "[0]" }, { in: "[1,0,2,0,3]", out: "[1,2,3,0,0]" }], "hard"),
    q("Remove Duplicates", "Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once. Return the number of unique elements.", "removeDuplicates", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,1,2]", out: 2 }, { in: "[0,0,1,1,1,2,2,3,3,4]", out: 5 }, { in: "[1,2,3]", out: 3 }], "hard"),
    q("Alice and Bob Stones", "Alice and Bob take turns taking 1, 2, or 3 stones from a pile of n stones. Alice goes first. The person who takes the last stone wins. Return true if Alice can win.", "canAliceWin", "Logic", "n", "int n", "int n", [{ in: 4, out: false }, { in: 1, out: true }, { in: 5, out: true }], "hard"),
    q("Alice and Bob Numbers", "Alice and Bob are playing a game with numbers. Given a number n, Alice can subtract any prime number p < n. Bob does the same. Return true if Alice wins.", "aliceBobNumbers", "Logic", "n", "int n", "int n", [{ in: 2, out: true }, { in: 4, out: true }, { in: 1, out: false }], "hard"),
    q("Alice and Bob Nim", "Given a pile of n stones, Alice and Bob take turns. Alice goes first. In each turn, a player can remove 1 to 3 stones. The player who cannot move loses. Return true if Alice wins.", "nimGame", "Logic", "n", "int n", "int n", [{ in: 4, out: false }, { in: 3, out: true }, { in: 8, out: false }], "hard"),
    q("Alice and Bob Divisors", "Given a number n, Alice starts. In each turn, a player chooses x such that 0 < x < n and n % x == 0 and replaces n with n - x. Return true if Alice wins.", "divisorGame", "Logic", "n", "int n", "int n", [{ in: 2, out: true }, { in: 3, out: false }, { in: 4, out: true }], "hard"),
    q("Missing Number", "Find the missing number in an array containing n distinct numbers in the range [0, n].", "missingNumber", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[3,0,1]", out: 2 }, { in: "[0,1]", out: 2 }, { in: "[9,6,4,2,3,5,7,0,1]", out: 8 }], "hard"),
    q("Power of Two", "Given an integer n, return true if it is a power of two.", "isPowerOfTwo", "Logic", "n", "int n", "int n", [{ in: 1, out: true }, { in: 16, out: true }, { in: 3, out: false }], "hard"),
    q("Factorial Logic", "Calculate the factorial of the integer n and return the result as an integer.", "factorial", "Logic", "n", "int n", "int n", [{ in: 5, out: 120 }, { in: 3, out: 6 }, { in: 0, out: 1 }], "hard"),
    q("Identify Prime", "Assess the integer n and return a boolean value indicating whether it is a prime number.", "isPrime", "Logic", "n", "int n", "int n", [{ in: 7, out: true }, { in: 4, out: false }, { in: 2, out: true }], "hard"),
    q("Anagram Check", "Determine if strings s1 and s2 are anagrams and return true or false.", "isAnagram", "Strings", "s1, s2", "string s1, string s2", "String s1, String s2", [{ in: "\"listen\"|\"silent\"", out: true }, { in: "\"a\"|\"b\"", out: false }, { in: "\"abc\"|\"cba\"", out: true }], "hard"),
    q("Palindrome Check", "Verify if the string s is a palindrome and return a boolean value.", "isPalindrome", "Strings", "s", "string s", "String s", [{ in: "\"aba\"", out: true }, { in: "\"abc\"", out: false }, { in: "\"racecar\"", out: true }], "hard"),
    q("Word Counter", "Count and return the total number of words in the string s.", "countWords", "Strings", "s", "string s", "String s", [{ in: "\"hello world\"", out: 2 }, { in: "\"one\"", out: 1 }, { in: "\"a b c\"", out: 3 }], "hard"),
    q("Single Number XOR", "Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.", "singleNumber", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[2,2,1]", out: 1 }, { in: "[4,1,2,1,2]", out: 4 }, { in: "[1]", out: 1 }], "hard"),
    q("Climbing Stairs", "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?", "climbStairs", "Logic", "n", "int n", "int n", [{ in: 2, out: 2 }, { in: 3, out: 3 }, { in: 4, out: 5 }], "hard"),
    q("Majority Element", "Find the element that appears more than n / 2 times in an array of size n.", "majorityElement", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[3,2,3]", out: 3 }, { in: "[2,2,1,1,1,2,2]", out: 2 }, { in: "[1]", out: 1 }], "hard"),
    q("Reverse Words Simple", "Return a new string where the order of words in string s is reversed.", "reverseWords", "Strings", "s", "string s", "String s", [{ in: "\"the sky is blue\"", out: "blue is sky the" }, { in: "\"hello world\"", out: "world hello" }, { in: "\"a good example\"", out: "example good a" }], "hard"),
    q("Parentheses Check", "Validate if string s contains a balanced sequence of parentheses, brackets, and braces.", "isValidPara", "Strings", "s", "string s", "String s", [{ in: "\"()[]{}\"", out: true }, { in: "\"(]\"", out: false }, { in: "\"([)]\"", out: false }], "hard"),
    q("Rotate Array Simple", "Rotate an integer array nums to the right by k steps, where k is non-negative.", "rotateArray", "Arrays", "nums, k", "vector<int>& nums, int k", "int[] nums, int k", [{ in: "[1,2,3,4,5]|2", out: "[4,5,1,2,3]" }, { in: "[-1,-100,3,99]|2", out: "[3,99,-1,-100]" }, { in: "[1]|0", out: "[1]" }], "hard"),
    q("Two Sum Logic", "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.", "twoSum", "Arrays", "nums, target", "vector<int>& nums, int target", "int[] nums, int target", [{ in: "[2,7,11,15]|9", out: "[0,1]" }, { in: "[3,2,4]|6", out: "[1,2]" }, { in: "[3,3]|6", out: "[0,1]" }], "hard"),
    q("Contains Duplicate", "Given an integer array nums, return true if any value appears at least twice in the array.", "containsDuplicate", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[1,2,3,1]", out: true }, { in: "[1,2,3,4]", out: false }, { in: "[1,1,1,3,3,4,3,2,4,2]", out: true }], "hard"),
    q("Max Subarray Simple", "Find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.", "maxSubArray", "Arrays", "nums", "vector<int>& nums", "int[] nums", [{ in: "[-2,1,-3,4,-1,2,1,-5,4]", out: 6 }, { in: "[1]", out: 1 }, { in: "[5,4,-1,7,8]", out: 23 }], "hard"),
    q("Binary to Int", "Convert the given binary string s into its equivalent base-10 integer and return it.", "binToInt", "Logic", "s", "string s", "String s", [{ in: "\"101\"", out: 5 }, { in: "\"111\"", out: 7 }, { in: "\"0\"", out: 0 }], "hard"),
    q("GCD Euclidean", "Calculate and return the greatest common divisor of the two integers a and b using the Euclidean algorithm.", "gcd", "Logic", "a, b", "int a, int b", "int a, int b", [{ in: "12|8", out: 4 }, { in: "17|5", out: 1 }, { in: "100|10", out: 10 }], "hard"),
    q("Armstrong Number", "Check if the integer n is an Armstrong number (a number that is the sum of its own digits each raised to the power of the number of digits).", "isArmstrong", "Logic", "n", "int n", "int n", [{ in: 153, out: true }, { in: 121, out: false }, { in: 370, out: true }], "hard"),
    q("Fibonacci Number", "Calculate the nth Fibonacci number, where F(0) = 0, F(1) = 1, and F(n) = F(n-1) + F(n-2).", "fib", "Logic", "n", "int n", "int n", [{ in: 2, out: 1 }, { in: 4, out: 3 }, { in: 0, out: 0 }], "hard"),
    q("FizzBuzz Variant", "Return 'Fizz' if n is divisible by 3, 'Buzz' if divisible by 5, 'FizzBuzz' if both, otherwise return n as a string.", "fizzBuzz", "Logic", "n", "int n", "int n", [{ in: 3, out: "\"Fizz\"" }, { in: 5, out: "\"Buzz\"" }, { in: 15, out: "\"FizzBuzz\"" }], "hard"),
    q("Digit Sum Logic", "Calculate the sum of the digits of the integer n.", "digitSum", "Logic", "n", "int n", "int n", [{ in: 123, out: 6 }, { in: 45, out: 9 }, { in: 9, out: 9 }], "hard"),
    q("Reverse Integer", "Given a signed 32-bit integer x, return x with its digits reversed.", "reverseInt", "Logic", "n", "int n", "int n", [{ in: 123, out: 321 }, { in: -123, out: -321 }, { in: 120, out: 21 }], "hard"),
    q("Count Vowel Cons", "Count and return the total number of vowels and consonants in the string s as an array [vowels, consonants].", "countVC", "Strings", "s", "string s", "String s", [{ in: "\"hello\"", out: "[2,3]" }, { in: "\"abc\"", out: "[1,2]" }, { in: "\"zzz\"", out: "[0,3]" }], "hard")
];

const seedDB = async () => {
    try {
        const uri = process.env.MONGO_URI || "mongodb://127.0.0.1:27017/deadlock";
        await mongoose.connect(uri, { dbName: 'Deadlock' });
        console.log("Connected to MongoDB:", uri);
        await DeadlockQuestion.deleteMany({});
        const all = [...EASY, ...MEDIUM, ...HARD];

        let inserted = 0;
        for (const item of all) {
            try {
                const question = new DeadlockQuestion(item);
                await question.save();
                inserted++;
            } catch (vErr) {
                console.log(`Validation Failed for: ${item.title}`);
                console.log(JSON.stringify(vErr.errors, null, 2));
                process.exit(1);
            }
        }

        console.log(`Successfully inserted ${inserted} strictly unique questions with professionally refined descriptions!`);
        process.exit(0);
    } catch (err) {
        console.error("Seeding failed:", err);
        process.exit(1);
    }
};

seedDB();
